### ISSUE TITLE
How To Clear Old State Machines

### ISSUE THREAD

**Issue by danieljlevine** [pytransitions/transitions-gui#17]
When I bring up a state machine in my web browser, often it's one left over from a previous run.  Even a different state machine will still bring up the left-over state machine in the browser.

Is there a call I should be making that clears these machines?  It would be great if each state machine could recall the manual layout I saved.

**Comment by aleneum** [comment]
Hello @danieljlevine,

this won't be relevant for you any longer but just for the sake of new users stumbling upon this issue:

>  It would be great if each state machine could recall the manual layout I saved.

As the documentation states:

> Layouts are stored by their name. If you plan to use transitions-gui with multiple state machines, it is recommended to make them distinguishable by name.

So if you plan to use multiple machines at the same time, give them different names:

```python
machine = WebMachine(
    states=states,
    initial="A",
    name="My first machine",  # <-- use e.g. "My second machine" 
    ordered_transitions=True,
    ignore_invalid_triggers=True,
    auto_transitions=False,
)
```

> Is there a call I should be making that clears these machines?

If your machine hast the same name as the previous one, `transitions-gui` will attempt to reuse the previously created layout. You have multiple ways of dealing with this. a) Pass the `?layout=concentric` (for simple FSM; `dagre` for HSMs) parameter as part of your URL since this will override stored layouts. Make sure to save the layout or otherwise your old layout will pop up the next time you reload the page *without* the layout parameter. b) Remove the local storage of `transitions-gui` from the browser. You can either nuke your whole website cache or clear the relevant item in your browsers `localStore` (see [here](https://stackoverflow.com/questions/7667958/clearing-localstorage-in-javascript)). The default key where layouts are stored is `transitions.layouts.machines`.
